### ISSUE TITLE
Some elements not styled in Zen Browser

### ISSUE THREAD

**Issue by ricjuhnl** [FrancoRav/whatsapp-web#3]
I'm using Whatsapp Web in Zen Browser 1.0.1-a.22 (Firefox 132.0.1) (64-bit).
- dark mode
- mocha
- accent color: mauve

During to reload the background is correct, but after it changes back to grey.
Also the sidebar for status, channels, community's is not themed.

![whatsapp-web](https://github.com/user-attachments/assets/c8857f71-0228-497b-a793-a608b5316112)

**Comment by FrancoRav** [comment]
Hi! I should change the README, but you should be using https://github.com/catppuccin/userstyles/tree/main/styles/whatsapp-web now. It's the same theme, but there are some fixes there that are not included in this repo. Thanks for the report, and let me know with an issue there if the problem is still not resolved after switching
